name: dart_code_metrics
version: 5.7.6
description: Software analytics tool that helps developers analyse and improve software quality.
homepage: https://dcm.dev/
repository: https://github.com/dart-code-checker/dart-code-metrics
issue_tracker: https://github.com/dart-code-checker/dart-code-metrics/issues
documentation: https://dcm.dev/docs/getting-started/

environment:
  sdk: '>=3.2.0 <4.0.0'

platforms:
  linux:
  windows:
  macos:

dependencies:
  analyzer: ">=5.1.0 <5.14.0"
  analyzer_plugin: ">=0.11.0 <0.12.0"
  ansicolor: ^2.0.2
  args: ^2.4.2
  collection: ^1.18.0
  crypto: ^3.0.3
  dart_code_metrics_presets: ^2.7.0
  file: ^7.0.0
  glob: ^2.1.2
  html: ">=0.15.0 <1.0.0"
  http: ^1.1.2
  meta: ^1.10.0
  path: ^1.8.3
  platform: ^3.1.4 # overridden for lowest versions compatibility
  pub_updater: ^0.4.0
  source_span: ^1.10.0
  uuid: ^4.0.0
  xml: ">=5.3.0 <7.0.0"
  yaml: ^3.1.2

dev_dependencies:
  coverage: ^1.7.2
  intl: ">=0.17.0 <0.19.0"
  lints: ^3.0.0
  mocktail: ^1.0.2
  test: ^1.25.0

  # internal package, used only in tests data
  test_lints:
    path: ./test/resources/test_lints

executables:
  metrics:
